[project]
name = "pymoex"
version = "0.1.1"
description = "API for work moex"
authors = [{ name = "Akxios" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
]
